#pragma once
//#define S_CLASS_NAME _xor_(L"ImGui Example").c_str()
#define S_HWIND_NAME _xor_(L"Loader").c_str()
#define S_MENU_BEGIN_NAME _xor_("Main Window").c_str()
#define S_MENU_HEAD_TEXT_NAME _xor_("Blatant Loader").c_str()
#define S_MENU_CLOSE_TEXT_NAME _xor_("X").c_str()
#define S_MENU_CHILD1_NAME _xor_("##loginForm").c_str()
#define S_MENU_LOGIN_NAME _xor_("Login:").c_str()
#define S_MENU_INPUT1_NAME _xor_("##userLogin").c_str()
#define S_MENU_PASSWORD_NAME _xor_("Password:").c_str()
#define S_MENU_INPUT2_NAME _xor_("##userPassword").c_str()
#define S_MENU_BTN1_NAME _xor_("Login").c_str()
#define S_MENU_CHILD2_NAME _xor_("##subs").c_str()
#define S_MENU_CHILD3_NAME _xor_("##leftSide").c_str()
#define S_MENU_PRODUCT_NAME _xor_("Products:").c_str()
#define S_MENU_CHILD4_NAME _xor_("##rightSide").c_str()
#define S_MENU_INFO_NAME _xor_("Info:").c_str()
#define S_MENU_EX_DATE_NAME _xor_("Expiration date: %s").c_str()
#define S_MENU_DESCR_NAME _xor_("Description: %s").c_str()
#define S_MENU_SUB_NAME _xor_("Subscription: %s").c_str()
#define S_MENU_ACTIVE_NAME _xor_("Active").c_str()
#define S_MENU_EXPIRED_NAME _xor_("Expired").c_str()
#define S_MENU_INJECT_NAME _xor_("Inject").c_str()
#define S_MENU_CONNECTED_NAME _xor_("Connected").c_str()
#define S_MENU_ERROR_CONNECTED_NAME _xor_("Error connection" ).c_str()
#define S_MENU_ERROR_NAME _xor_(" -> Error: %s").c_str()

#define S_INJ_ALLOC_MEM _xor_("NtAllocateVirtualMemory").c_str()
#define S_INJ_CREATE_THREAD _xor_("NtCreateThreadEx").c_str()
#define S_INJ_OPEN_PROCESS _xor_("ZwOpenProcess").c_str()
#define S_INJ_WRITE_MEM _xor_("NtWriteVirtualMemory").c_str()
#define S_INJ_NTDLL _xor_("ntdll.dll").c_str()
#define S_INJ_LDR_LOAD_DLL  _xor_("LdrLoadDll").c_str()
#define S_INJ_INIT_UNICODE_STR _xor_("RtlInitUnicodeString").c_str()
#define S_INJ_INIT_INFOPROCESS_STR _xor_("NtQueryInformationProcess").c_str()
#define S_INJ_SET_INFO_THREAD _xor_("NtSetInformationThread").c_str()
#define S_INJ_INIT_ANSY_STR _xor_("RtlInitAnsiString").c_str()
#define S_INJ_ANSY_TO_UNI _xor_("RtlAnsiStringToUnicodeString").c_str()
#define S_INJ_GET_PROC_ADDR _xor_("LdrGetProcedureAddress").c_str()

#define S_API_LOGIN_ENDPOINT _xor_("/api/auth/v1/client-login")
#define S_API_SUB_ENDPOINT _xor_("/api/user/subs")
#define S_API_HEALTH_ENDPOINT _xor_("/api/health")
#define S_API_HEALTH_RESPONSE _xor_("OK").c_str()
#define S_API_LOAD_SUB _xor_("/api/sub/load-sub/").c_str()
#define S_API_SECURITY_DBG_INFO _xor_("/api/security/debug")
#define S_API_SECURITY_INFO _xor_("/api/security/info")

#define S_DTO_DATA _xor_("data").c_str()
#define S_DTO_PASSWORD _xor_("password").c_str()
#define S_DTO_LOGIN _xor_("login").c_str()
#define S_DTO_HWID _xor_("hwid").c_str()
#define S_DTO_TOKEN _xor_("accessToken").c_str()
#define S_DTO_ID _xor_("id").c_str()
#define S_DTO_EX_DATE _xor_("expirationDate").c_str()
#define S_DTO_ACTIVE _xor_("active").c_str()
#define S_DTO_PRODUCT_ID _xor_("productId").c_str()
#define S_DTO_NAME _xor_("name").c_str()
#define S_DTO_DESCR _xor_("description").c_str()
#define S_DTO_STATUS _xor_("status").c_str()
#define S_DTO_HASH _xor_("hash").c_str()
#define S_DTO_ALT_ANAME _xor_("altName").c_str()

#define S_EMPTY_STR _xor_("{}").c_str()